### ISSUE TITLE
Need Promise based enumerateDevices API

### ISSUE THREAD

**Issue by MikeBlair** [DoubangoTelecom/webrtc-plugin#11]
Please expose a Promise based enumerateDevices API

**Comment by DoubangoTelecom** [comment]
Already returning a promise. Sample: https://doubango.org/rtc-plugin/samples/src/content/devices/input-output/
Please explain what you mean by "expose".

**Comment by MikeBlair** [comment]
My team will provide more info on this tomorrow.

**Comment by MikeBlair** [comment]
We are working on a sample to show you this issue.

**Comment by ptownsend** [comment]
This seems to be related to issue https://github.com/DoubangoTelecom/webrtc-plugin/issues/15.

The object returned by this function does not work like a promise is expected to, and breaks promise chains when attempting to `.then` after the initial `.then` and `.catch`.

Please see the example here: https://ptownsend.github.io/enumerate-devices-test.html

Try in Chrome, then in IE using the plugin.

The temasys plugin returns a promise as expected, if you try in IE here: https://ptownsend.github.io/enumerate-devices-temasys.html

**Comment by DoubangoTelecom** [comment]
Fix is part of installer 1.2.0: https://doubango.org/rtc-plugin/setup.exe
You should see empty strings on the webpage but correct ones in the console logs. Related to issue #17
