### ISSUE TITLE
Canvas API

### ISSUE THREAD

**Issue by MikeBlair** [DoubangoTelecom/webrtc-plugin#13]
Canvas API needs to support:

requestAnimationFrame
canvas.captureStream

This is lower priority than the other issues, but it needs to be resolved.

Filed by: Mike Blair @ Lifesize

**Comment by DoubangoTelecom** [comment]
This is not part of WebRTC

**Comment by MikeBlair** [comment]
@DoubangoTelecom you're right, it isn't.  We need to figure out a workaround on our side for these not being available on IE11.  I'll close this, and we may discuss a workaround with you via Bobby.
