### ISSUE TITLE
getUserMedia doesn't accept preferred height and width constraints

### ISSUE THREAD

**Issue by ptownsend** [DoubangoTelecom/webrtc-plugin#14]
Passing `getUserMedia` the constraints `{ audio: true, video: { width: 1280, height: 720 } }` as described in [MDN](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia) throws an exception in IE when using the plugin. 

See the example on my github.io page here: https://ptownsend.github.io/constraints-test.html

**Comment by DoubangoTelecom** [comment]
Fix is part of the installer version 1.2.0: https://doubango.org/rtc-plugin/setup.exe
Please note that according to https://www.w3.org/TR/mediacapture-streams/#idl-def-MediaStreamConstraints, the constraints you're using to test the 'exact' usecase isn't correct. Both Chrome and IE are ignoring it (see chrome://webrtc-internals/).
You're using: { audio: true, video: { exact: { height: 1920, width: 1080 } } }
Should be: { audio: true, video: {width: {exact: 1080}, height: {exact: 1920}} }
