### ISSUE TITLE
getUserMedia returned value doesn't appear to be a promise

### ISSUE THREAD

**Issue by ptownsend** [DoubangoTelecom/webrtc-plugin#15]
Using the plugin, the value returned from `navigator.mediaDevices.getUserMedia` can be `.then`'ed and `.catched`'ed, but the value returned from at least the `.catch` is not a promise, breaking promise chains.

See the example on my github.io page here: https://ptownsend.github.io/constraints-test.html
And specifically these lines: https://github.com/ptownsend/ptownsend.github.io/blob/master/js/main.js#L51-L58

**Comment by DoubangoTelecom** [comment]
For sure what is returned is a promise (IPromise ATL object): https://github.com/DoubangoTelecom/webrtc-plugin/blob/6be6ae374f65ca4ed5dfd053b98b3f7ccacc62e0/Promise.cxx#L61
