### ISSUE TITLE
Plugin appears unstable around refreshing the page -- causes IE tab to crash

### ISSUE THREAD

**Issue by ptownsend** [DoubangoTelecom/webrtc-plugin#16]
There are a couple of scenarios that appear to cause the plugin to crash the IE tab, all of which seem to revolve around refreshing the tab. I'm using Windows 10 with IE11. 

You can reproduce these scenarios in my constraints test here: 
https://ptownsend.github.io/constraints-test.html

### 1: 
- Click the `Exact` button to capture the camera
- Refresh the page
- Internet Explorer has stopped working

### 2:
- Click the `Exact` button to capture the camera
- Click the `Stop` button to stop the capture
- Refresh the page
- Click the `Exact` button
  - Notice the camera does not capture successfully
- Click the `Exact` button again
- Internet Explorer has stopped working

**Comment by DoubangoTelecom** [comment]
In your report you don't say if the crash happens all the time or you have to try several times. In my case I've to try several times to reproduce the crash. So, I don't know if it's the same bug or not. The fix will be part of the next release so that you can check

**Comment by DoubangoTelecom** [comment]
Fix is part of installer version 1.2.0:  https://doubango.org/rtc-plugin/setup.exe
