### ISSUE TITLE
Getting error: Object doesn't support property or method 'createMediaStream'

### ISSUE THREAD

**Issue by ptownsend** [DoubangoTelecom/webrtc-plugin#18]
Using version 1.2 of the plugin, I'm getting this exception:
````
Object doesn't support property or method 'createMediaStream'
````
when attempting to call `new MediaStream()`

![image](https://cloud.githubusercontent.com/assets/1615860/26650135/15a3aa6e-460e-11e7-9cea-9b339034fa8e.png)

Referencing this line of your adapter.js:

<img width="459" alt="screen shot 2017-05-31 at 2 35 46 pm" src="https://cloud.githubusercontent.com/assets/1615860/26650284/85f14b64-460e-11e7-8f97-fa89a68ce5e9.png">

**Comment by DoubangoTelecom** [comment]
On my tests it's working (Win10/IE11 and Win8/IE9). The function exist: https://github.com/DoubangoTelecom/webrtc-plugin/blob/6be6ae374f65ca4ed5dfd053b98b3f7ccacc62e0/Plugin.cxx#L511
Please attach the full js logs.
Also make sure you're using latest adapter.js (version 1.1.4).
Go to C:\Users\<your windows username>\AppData\Roaming\webrtc-plugin and check that both ./rtc.dll and x64\rtc.dll have the right version numbers (righ click -> Properties -> Details)

**Comment by DoubangoTelecom** [comment]
Also, to check that you're using the latest version try your sample [1] to see if it works now. If yes, this means your dlls are up2date
[1] https://ptownsend.github.io/constraints-test.html

**Comment by ptownsend** [comment]
Ah -- yes, that was the issue -- either the uninstall process or the installer didn't clean up or overwrite one of those dlls. Manually deleting them from that directory and reinstalling the plugin worked.

Thanks!
