### ISSUE TITLE
Missing MediaStream functionality

### ISSUE THREAD

**Issue by MikeBlair** [DoubangoTelecom/webrtc-plugin#7]
MediaStream() constructor should be available on the window object.

MediaStream object needs to expose:
- getAudioTracks
- getVideoTracks
- addTrack
- removeTrack

Filed by: Mike Blair @ Lifesize

**Comment by DoubangoTelecom** [comment]
All these methods are already implemented except the constructor: https://github.com/DoubangoTelecom/webrtc-plugin/blob/master/MediaStream.cxx
Which kind of issue do you have?

**Comment by ptownsend** [comment]
We just need the constructor made available to us -- we have several places where we create empty MediaStream objects in order to populate with tracks later.

**Comment by MikeBlair** [comment]
@DoubangoTelecom, having this helps IE 11 act like Chrome w WebRTC

**Comment by DoubangoTelecom** [comment]
Added the default constructor (no args) in plugin version 1.1.0 and adapter.js version 1.1.2.
https://www.w3.org/TR/mediacapture-streams/#widl-ctor-MediaStream
