### ISSUE TITLE
getUserMedia missing

### ISSUE THREAD

**Issue by MikeBlair** [DoubangoTelecom/webrtc-plugin#8]
getUserMedia should be available on the navigator and window objects

Filed by: Mike Blair @ Lifesize

**Comment by DoubangoTelecom** [comment]
This is no longer the case: https://www.w3.org/TR/mediacapture-streams/#navigatorusermedia-interface-extensions

**Comment by DoubangoTelecom** [comment]
Sample: https://doubango.org/rtc-plugin/samples/src/content/getusermedia/gum/

**Comment by MikeBlair** [comment]
Closing this.
