### ISSUE TITLE
Method to check plugin version

### ISSUE THREAD

**Issue by MikeBlair** [DoubangoTelecom/webrtc-plugin#9]
There needs to be a method to check if the plugin is successfully loaded and a way to get the current plugin version so we can tell if the plugin needs to be upgraded.

Filed by: Mike Blair @ Lifesize

**Comment by DoubangoTelecom** [comment]
Using adapter.js version 1.1.2:
To detect when the plugin is loaded:
```
document.addEventListener("webrtcloaded", function() {
      });
```
To get the plugin version:
```
getWebRTCPlugin().versionName
```
